Private events APP development
carlos-osorio-developer/private-events-app pull request #1
Opened 2021-05-27 16:29 UTC by carlos-osorio-developer

## Add features for:

- User MVC.
- Event MVC.
- Associations between both models with has_many through the "Attending" table.
- Authentication methods.
- Navbar and navigation.
- Tests.

2021-05-27 19:52 UTC, NtwaliHeritier requested changes
### **STATUS: CHANGES REQUESTED🛑🛑🛑**

Hello @carlos-osorio-developer 
Great work making this project.
I can tell you put in a lot of effort. I like how events are separated.
However, let's make minor changes and get it approved.

[REQUIRED]: The attend button is not working. Kindly fix it.
[REQUIRED]: The logout button is not working. Kindly fix it.
[REQUIRED]: Kindly add unit and integration tests.

You can find the other requirements below.

Make the required changes and ask for another review👍👍
Happy coding💻💻

2021-05-27 19:53 UTC, NtwaliHeritier commented on app/controllers/events_controller.rb
> +  end
The index action should have these two lines. 
lists past events, i.e. @past_events = Event.previous_events (screenshot from Odin)
lists ucomping events, i.e. @upcoming_events = Event.upcoming_events (screenshot from Odin)

2021-05-27 19:55 UTC, NtwaliHeritier commented on app/controllers/users_controller.rb
> +  end
The show action should have these lines.

lists events created by user, i.e. `@created_events = current_user.events` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/current_user_show_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations))

lists events previoulsy attendented by user **using event model scope**, i.e. `@past_events = current_user.attended_events.previous` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/user_events_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations))

lists upcoming events previously attended by user **using event model scope**, i.e. `@upcoming_events = current_user.attended_events.upcoming` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/user_events_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations))

2021-05-27 20:41 UTC, carlos-osorio-developer commented on app/controllers/users_controller.rb
> +  end
> The show action should have these lines.
> 
> lists events created by user, i.e. `@created_events = current_user.events` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/current_user_show_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations))
> 
> lists events previoulsy attendented by user **using event model scope**, i.e. `@past_events = current_user.attended_events.previous` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/user_events_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations))
> 
> lists upcoming events previously attended by user **using event model scope**, i.e. `@upcoming_events = current_user.attended_events.upcoming` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/user_events_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations))

 - Can you be more specific with "logout button is not workin"? It's working here.
 - What do you mean by "unit and integration test"?
- Also, I can not see any of those screenshots in the project specifics: https://www.theodinproject.com/paths/full-stack-ruby-on-rails/courses/ruby-on-rails/lessons/associations

Thanks.

2021-05-27 21:46 UTC, NtwaliHeritier requested changes
### **STATUS: CHANGES REQUESTED🛑🛑**

Hello again @carlos-osorio-developer 
Great work making most of the required changes.
However to get it approved you must make all the required changes👍👍

Kindly make all the changes required in the previous review and ask for another review👌👌

Happy coding💻💻

2021-05-27 22:08 UTC, carlos-osorio-developer commented
Sorry but those changes don't reflect the specifications provided by the documentation, please go to the link and check it yourself.

https://www.theodinproject.com/paths/full-stack-ruby-on-rails/courses/ruby-on-rails/lessons/associations

2021-05-27 22:11 UTC, carlos-osorio-developer commented
Sorry but those changes don't reflect the specifications provided by the documentation, please go to the link and check it yourself.

https://www.theodinproject.com/paths/full-stack-ruby-on-rails/courses/ruby-on-rails/lessons/associations

The changes that you are asking for are not in the project specifications.

2021-05-27 22:17 UTC, carlos-osorio-developer commented
![image](https://user-images.githubusercontent.com/78050026/119904000-3b957f80-bf0f-11eb-82a2-fa98d6e7d77d.png)

![image](https://user-images.githubusercontent.com/78050026/119904047-50721300-bf0f-11eb-9064-f6f91165d106.png)

2021-05-27 22:27 UTC, carlos-osorio-developer commented
Kindly look at the screenshots from the original website.

Kindly enter the link provided before. 

https://www.theodinproject.com/paths/full-stack-ruby-on-rails/courses/ruby-on-rails/lessons/associations

2021-05-27 23:37 UTC, sinansevgi requested changes
# Changes Required :recycle: 
------

Hi @carlos-osorio-developer , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

### Looks like The Odin Project updated their project specification 2 days ago. Please check [this link ](https://github.com/TheOdinProject/curriculum/blob/e71e03d984bc0b2c3d251a7cbcf9721c796b4175/rails_programming/advanced_forms_and_activerecord/project_associations.md) for previous description. 

I am so sorry for this confusion. 

## Required Changes ♻️
_Please check the inline comments made by previous TSE_ 

Happy Hacking! :computer: 

-----

You can reply to this conversation if you have any questions or need elaboration. :wave: 
Sinan Sevgi

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-05-27 23:37 UTC, sinansevgi commented on app/controllers/events_controller.rb
> +  end
- [ ] Please check the project specification link that I share. You can see this requirement in there

2021-05-27 23:37 UTC, sinansevgi commented on app/controllers/users_controller.rb
> +  end
- [ ] Please check the project specification link that I share. You can see these requirements there

2021-05-27 23:38 UTC, sinansevgi commented on app/controllers/users_controller.rb
> +  end
- [ ] Please check the project specification link that I share. You can see these requirements there

2021-05-27 23:38 UTC, sinansevgi commented on app/controllers/events_controller.rb
> +  end
- [ ] Please check the project specification link that I share. You can see these requirements there

2021-06-01 19:47 UTC, carlos-osorio-developer commented
If The Odin Project updated their project, you should update your reviews. I had no way to know that before actually did the project. Use your common sense.

Also, the requirements of the previous app and the current one are the same, and they function exactly the same.

2021-06-02 06:58 UTC, emmanuellekamwa approved these changes
Hi team. Congrats on implementing all the necessary changes 👏🏽👏🏽. Your project looks great and it is approved 🎉🎉. Good luck with the next projects and happy coding 👨🏽‍💻👨🏽‍💻🚀🚀

2021-06-02 14:04 UTC, merged